{
    'name': "Approval Request | Multi Level Approval Request",
    'version': "14.0.0.0",
    'category': "Extra Tools",
    'license': 'OPL-1',
    'summary': "All in one approval app request for approval request approve request travel approval generic approve generic multi level approval request multi level approval multiple approval multiple level request multi level request approval request multi approval app",
    'description': """The Multi Level Approval Odoo App helps users to streamline the approval process in business. This app allows users to set up multiple request types, and multiple approvers for various request types this ensures that each approval is reviewed and approved by the appropriate person so the approval process is efficient and effective.""",
    'author': "BrowseInfo",
    "website": "https://www.browseinfo.com",
    "price": 35,
    "currency": 'EUR',
    'depends': ['base', 'web', 'mail', 'product', 'purchase', "l10n_th_amount_to_text"],
    'data': [
        'security/approval_type.xml',
        'security/approval_security.xml',
        'security/ir.model.access.csv',
        'wizard/file_attachment_wizard_view.xml',
        'views/approval_req_view.xml',
        'views/approval_type_view.xml',
        "reports/footer.xml",
        "reports/paper_format.xml",
        "reports/action_reports.xml",
        'views/my_approvals_view.xml',
        'reports/report_my_approval_template.xml',
        'views/approval_request_view.xml',
        'views/mail_template_refuse_view.xml',
        'views/mail_template_approved_view.xml',
        'views/mail_template_request_view.xml',
        'views/purchase_order_views.xml',
        'views/approval_name_approval_type_view.xml',

    ],
    'assets': {
        'web.assets_backend': [
            'bi_approval_app/static/src/scss/your_styles.scss',
        ],
    },
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,
    'live_test_url': 'https://youtu.be/6wxIwXVLQCQ',
    "images": ['static/description/Banner.gif'],
}
