# Copyright 2019 Ecosoft Co., Ltd (http://ecosoft.co.th/)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html)

{
    'name': 'PFB Module Budget Install Standard ',
    'version': '14.0.2',
    'author': 'PFB',
    'license': 'AGPL-3',
    'website': '',
    'category': 'Modules',
    'depends': [
        'psn_budget',
        'budget_activity',
        'budget_activity_advance_clearing',
        'budget_activity_contract',
        'budget_activity_expense',
        'budget_activity_purchase',
        'budget_activity_purchase_request',
        'budget_allocation',
        'budget_allocation_dimension',
        'budget_allocation_dimension_advance_clearing',
        'budget_allocation_dimension_expense',
        'budget_allocation_dimension_fund',
        'budget_allocation_dimension_purchase',
        'budget_allocation_dimension_purchase_request',
        'budget_allocation_fund',
        'budget_allocation_fund_advance_clearing',
        'budget_allocation_fund_department',
        'budget_allocation_fund_expense',
        'budget_allocation_fund_operating_unit',
        'budget_allocation_fund_operating_unit_access_all',
        'budget_allocation_fund_purchase',
        'budget_allocation_fund_purchase_request',
        'budget_allocation_fund_revision',
        'budget_allocation_plan_revision',
        'budget_allocation_transfer',
        'budget_control',
        'budget_control_advance_clearing',
        'budget_control_consumed_plan',
        'budget_control_contract',
        'budget_control_department',
        'budget_control_exception',
        'budget_control_expense',
        'budget_control_operating_unit',
        'budget_control_operating_unit_access_all',
        'budget_control_purchase',
        'budget_control_purchase_request',
        'budget_control_revision',
        'budget_control_revision_department',
        'budget_control_revision_operating_unit',
        'budget_control_revision_operating_unit_access_all',
        'budget_control_revision_project',
        'budget_control_rolling',
        'budget_control_rolling_revision',
        'budget_control_sequence',
        'budget_control_transfer',
        'budget_control_transfer_dimension',
        'budget_control_transfer_dimension_constraint',
        'budget_control_transfer_fund',
        'budget_control_transfer_operating_unit',
        'budget_control_transfer_operating_unit_access_all',
        'budget_dimension',
        'budget_dimension_advance',
        'budget_dimension_expense',
        'budget_dimension_purchase',
        'budget_dimension_purchase_request',
        'budget_generate_analytic',
        'budget_job_order',
        'budget_job_order_consumed_plan',
        'budget_job_order_contract',
        'budget_job_order_expense',
        'budget_job_order_purchase',
        'budget_job_order_purchase_request',
        'budget_plan',
        'budget_plan_excel',
        'budget_plan_revision',
        'budget_source_fund',
        'mis_builder_budget',
        'mis_builder_budget_activity_group',
        'res_project_monitoring',
    ],
    'installable': True,
}
