{
    'name': 'บ้านเขียว',
    'version': '1.0',
    'summary': 'จัดการข้อมูลพนักงานบ้านเขียว',
    'description': 'โมดูลบ้านเขียวสำหรับจัดการข้อมูลพนักงาน',
    'author': 'บ้านเขียว',
    'category': 'Human Resources',
    'depends': ['base','branch','npd_remote_scrap_api'],
    'data': [
        'security/ir.model.access.csv',
        'views/baankheaw_employee_views.xml',
        'views/realtime_debtor_template.xml',
        'views/realtime_quotation_template.xml',
        'views/realtime_quotation_summary_view.xml',
        'views/stock_daily_report_views.xml',
        'views/rental_stock_summary_view.xml',
        'views/total_rental_stock_view.xml',
        'views/rental_invoice_receipt_view.xml',
        'views/bill_arrears_summary_template.xml',
        'views/product_stock_summary.xml',
        'views/old_customer_summary_view.xml',
        'views/rental_quotation_view.xml',
        'views/receive_payment_view.xml',
        'views/product_stock_summary_day.xml',
        'views/debtor_all_summary_view.xml',
    ],
    'installable': True,
    'application': True,
    'images': ['static/description/icon.png'],
}

