{
    'name': 'Employee Salary',
    'version': '1.0',
    'summary': 'Manage employee salary and check-in radius',
    'category': 'Human Resources',
    'author': 'Your Name',
    'website': 'https://www.yourwebsite.com',
    'depends': ['hr'],
    'data': [
        'security/ir.model.access.csv',
        'views/employee_salary_view.xml',
        'views/leave_type_views.xml',
        'views/work_schedule_views.xml',
        'views/hr_checkin_distance_views.xml',
        'views/approver_relations_views.xml',
        'views/commission_detail_wizard_view.xml',
        'views/commission_rate_config_views.xml',
        'views/commission_branch_config_views.xml',
        'views/commission_rate_branch_sales_views.xml',
        'views/commission_sale_headoffice_views.xml',
        'views/payroll_salary_view.xml',
        'views/payroll_holiday_view.xml',
        'views/department_views.xml',
        'views/position_views.xml',
        'views/branch_views.xml',
        'views/payroll_period_views.xml',
        'views/medical_expense_views.xml',
        'views/employee_warning_view.xml',
        'views/other_income_view.xml',
        'views/work_security_deposit_views.xml',
        'views/allowance_management_views.xml',
        'views/saturday_leave_config_views.xml',
        'views/menu_items.xml',
        'reports/payslip_report.xml',
        'data/payroll_cron.xml',
        'data/leave_entitlement_cron.xml',
        'data/commission_rate_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
