{
    "name": "PFB Standard : Show only child",
    "summary": "",
    "version": "14.0.1.0.1",
    "category": "",
    "author": "Perfect Blending",
    "website": "https://www.perfectblending.com",
    "depends": ["sale",
                "account",
                "psn_is_customer_is_vendor",
                "account_billing",
                "purchase_request",
                "account_cheque",
                "purchase",
                "l10n_th_tax_invoice",
                "l10n_th_withholding_tax_cert",
                "purchase_work_acceptance",
                ],
    "data": [
        'views/sale_order.xml',
        'views/invoice.xml',
        'views/billing.xml',
        'views/cheque.xml',
        'views/purchase.xml',
        'views/purchase_request.xml',
        'views/without.xml',
        #'views/account_payment.xml',
    ],

    "installable": True,
    "auto_install": False,
}
