# Copyright 2019 Ecosoft Co., Ltd (http://ecosoft.co.th/)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html)

{
    'name': 'PFB Module Install Standard ',
    'version': '14.0.1',
    'author': 'PFB',
    'license': 'AGPL-3',
    'website': '',
    'category': 'Modules',
    'depends': [
        'sale',
        'purchase',
        'account',
        'stock',
        'base_address_city',
        'l10n_th_tin_service',
        'l10n_th_tax_invoice',
        'l10n_th_tax_report',
        'l10n_th_withholding_tax_cert_form',
        'l10n_th_withholding_tax_report',
        'account_config',
        'withholding_tax_cert_amount',
        'payment_method',
        'account_cheque',
        'account_config',
        'account_payment_invoice',
        'account_voucher',
        'petty_cash',
        'account_advance',
        'account_billing_advance',
        'account_payment_sequence',
        'pfb_account_move',
        'pfb_product_name_unq',
        'pfb_vendor_priority',
        'purchase_isolated_seq_date',
        'purchase_requests_seq_date',
        'sale_isolated_quotation_seq_date',
        'account_dynamic_reports',
        'web_responsive',
        'account_asset_management',
        'account_chart_update',
        'account_fiscal_year',
        'account_invoice_date_due',
        'account_invoice_force_number',
        'account_invoice_line_report',
        'account_invoice_refund_link',
        'account_invoice_search_by_reference',
        'account_invoice_start_end_dates',
        'account_fiscal_year_closing',
        'account_journal_lock_date',
        'account_journal_sequence_date',
        'account_journal_sequences',
        'account_lock_date_update',
        'account_move_force_removal',
        'account_move_line_menu',
        'account_move_line_tax_editable',
        'account_move_template',
        'purchase_cancel_reason',
        'purchase_commercial_partner',
        'purchase_delivery_split_date',
        'account_menu',
        'account_debit_note',
        'account_cutoff_start_end_dates',
        'date_range',
        'stock_force_date_app',
        'ks_account_dashboard',
        'ks_dashboard_ninja',
        'ks_inventory_dashboard',
        'ks_sale_dashboard_ninja',
        'ks_dn_advance',
        'purchase_deposit',
        'sale_outgoing_product',
        'sale_product_category_menu',
        'sale_product_multi_add',
        'sale_product_set',
        'sale_product_set_packaging_qty',
        'sale_purchase',
        'sale_shipping_info_helper',
        'sale_stock',
        'sale_stock_picking_blocking',
        'sales_team',
        'stock_card_report',
        'stock_delivery_note',
        'stock_demand_estimate',
        'stock_demand_estimate_matrix',
        'stock_free_quantity',
        'stock_move_location',
        'stock_no_negative',
        'stock_picking_invoice_link',
        'stock_picking_line_sequence',
        'stock_picking_report_valued',
        'stock_pull_list',
        'stock_quant_manual_assign',
        'stock_request',
        'stock_request_tier_validation',
        'stock_warehouse_calendar',
        'psn_account_menu',
        'web_refresher',
        'dms',
        'purchase_request',
        'purchase_rfq_number',
        'purchase_request_department',
        'partner_aging',
        'account_lock',
        'purchase_invoice_plan',
        'sale_invoice_plan',
        'purchase_last_price_info',
        'account_edi',
    ],
    'installable': True,
}
